name: Try github.event on issue
on: issues
jobs:
    print-event:
        runs-on: ubuntu-latest
        steps:
            - name: Print github.event
              run: echo "${{ toJSON(github.event) }}"
              